#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-FCGI-ProcManager
Version  : 0.28
Release  : 29
URL      : https://cpan.metacpan.org/authors/id/A/AR/ARODLAND/FCGI-ProcManager-0.28.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/A/AR/ARODLAND/FCGI-ProcManager-0.28.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libf/libfcgi-procmanager-perl/libfcgi-procmanager-perl_0.28-1.debian.tar.xz
Summary  : 'A perl-based FastCGI process manager'
Group    : Development/Tools
License  : LGPL-2.1
Requires: perl-FCGI-ProcManager-license = %{version}-%{release}
Requires: perl-FCGI-ProcManager-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
General Information
-------------------
FCGI-ProcManager is a process manager for FCGI.  By implementing the
process manager in perl, we can more finely tune FastCGI performance, and
we can take CPU and memory advantages of fast forks and copy-on-write UNIX
process management characteristics.

%package dev
Summary: dev components for the perl-FCGI-ProcManager package.
Group: Development
Provides: perl-FCGI-ProcManager-devel = %{version}-%{release}
Requires: perl-FCGI-ProcManager = %{version}-%{release}

%description dev
dev components for the perl-FCGI-ProcManager package.


%package license
Summary: license components for the perl-FCGI-ProcManager package.
Group: Default

%description license
license components for the perl-FCGI-ProcManager package.


%package perl
Summary: perl components for the perl-FCGI-ProcManager package.
Group: Default
Requires: perl-FCGI-ProcManager = %{version}-%{release}

%description perl
perl components for the perl-FCGI-ProcManager package.


%prep
%setup -q -n FCGI-ProcManager-0.28
cd %{_builddir}
tar xf %{_sourcedir}/libfcgi-procmanager-perl_0.28-1.debian.tar.xz
cd %{_builddir}/FCGI-ProcManager-0.28
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/FCGI-ProcManager-0.28/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-FCGI-ProcManager
cp %{_builddir}/FCGI-ProcManager-0.28/COPYING %{buildroot}/usr/share/package-licenses/perl-FCGI-ProcManager/70bc76011ca22ca19dc2f311422fd2abd1639284
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-FCGI-ProcManager/d3c0a81c50f2d3bff1ffb0fd24ed40ba471fb676
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/FCGI::ProcManager.3
/usr/share/man/man3/FCGI::ProcManager::Constrained.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-FCGI-ProcManager/70bc76011ca22ca19dc2f311422fd2abd1639284
/usr/share/package-licenses/perl-FCGI-ProcManager/d3c0a81c50f2d3bff1ffb0fd24ed40ba471fb676

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
