#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-FCGI-ProcManager
Version  : 0.28
Release  : 6
URL      : https://cpan.metacpan.org/authors/id/A/AR/ARODLAND/FCGI-ProcManager-0.28.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/A/AR/ARODLAND/FCGI-ProcManager-0.28.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libf/libfcgi-procmanager-perl/libfcgi-procmanager-perl_0.28-1.debian.tar.xz
Summary  : 'A perl-based FastCGI process manager'
Group    : Development/Tools
License  : LGPL-2.1
Requires: perl-FCGI-ProcManager-license = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
General Information
-------------------
FCGI-ProcManager is a process manager for FCGI.  By implementing the
process manager in perl, we can more finely tune FastCGI performance, and
we can take CPU and memory advantages of fast forks and copy-on-write UNIX
process management characteristics.

%package dev
Summary: dev components for the perl-FCGI-ProcManager package.
Group: Development
Provides: perl-FCGI-ProcManager-devel = %{version}-%{release}

%description dev
dev components for the perl-FCGI-ProcManager package.


%package license
Summary: license components for the perl-FCGI-ProcManager package.
Group: Default

%description license
license components for the perl-FCGI-ProcManager package.


%prep
%setup -q -n FCGI-ProcManager-0.28
cd ..
%setup -q -T -D -n FCGI-ProcManager-0.28 -b 1
mkdir -p deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/FCGI-ProcManager-0.28/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-FCGI-ProcManager
cp COPYING %{buildroot}/usr/share/package-licenses/perl-FCGI-ProcManager/COPYING
cp deblicense/copyright %{buildroot}/usr/share/package-licenses/perl-FCGI-ProcManager/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.1/FCGI/ProcManager.pm
/usr/lib/perl5/vendor_perl/5.28.1/FCGI/ProcManager/Constrained.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/FCGI::ProcManager.3
/usr/share/man/man3/FCGI::ProcManager::Constrained.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-FCGI-ProcManager/COPYING
/usr/share/package-licenses/perl-FCGI-ProcManager/deblicense_copyright
